name: MorphRedeem
version: 1.3.0
main: net.naturva.morphie.mr.MorphRedeem
author: Morphie
api-version: 1.13
depend: [mcMMO]
softdepend: [PlaceholderAPI]
commands:
   morphredeem:
    description: Main command for the MorphRedeem plugin!
    usage: /<command>
    aliases: [mr, redeem]